### PR TITLE
Updates for ins/del requirements making this Candidate Change 5.

### PR DESCRIPTION
**Pull request by gkellogg**
This makes the changes appropriate for class-3 (although the changes being split between different sections is novel).

@iherman may have some suggestions on better ways to draw together the different insertions and deletions.

Note that I rebased against main, so this will be a force-push.

### CODE REVIEW

**Comment by iherman** [comment]
Is there a preview of the results? The change files all seem to be configuration files and codes which, I presume, you use as some sort of back-end. This is fairly difficult to follow for humans :-)

**Comment by gkellogg** [comment]
Because this is a PR to a branch in @anatoly-scherbakov’s branch on his fork of the repo, PR Preview is not available.

merging this would be easier if the target branch were rebased to “main”. Once merged, the normal PR preview link should work.

**Comment by gkellogg** [comment]
Here's a [Githack link](https://raw.githack.com/gkellogg/json-ld-api/605-json-serialization/index.html#change_5) to the rendered document pointing at "CANDIDATE CORRECTION 5".

**Comment by iherman** [comment]
> Here's a [Githack link](https://raw.githack.com/gkellogg/json-ld-api/605-json-serialization/index.html#change_5) to the rendered document pointing at "CANDIDATE CORRECTION 5".

Thanks.

Basically, it works for me; my only comments are editorial/readability. I had two problems

1. In some case the "Candidate Correction" box is put several lines "before" the actual change. This has some logic when it comes to algorithms, but...
2. The color contrast with the new text (green of some flavor) is such that it is not easy to see the changes

The combination of these two comments mean that, in some cases, it is fairly difficult to locate the real change, and that beats the purpose a bit. I think that, in this case (I guess this may be the problem with the algorithm style, I am not sure) maybe a more effective color contrast would make it better.

(Note that these colors work very well if you use dark mode for the spec. Sigh, it is difficult....)

**Comment by gkellogg** [comment]
> 1. In some case the "Candidate Correction" box is put several lines "before" the actual change. This has some logic when it comes to algorithms, but...
> 2. The color contrast with the new text (green of some flavor) is such that it is not easy to see the changes
> 
> The combination of these two comments mean that, in some cases, it is fairly difficult to locate the real change, and that beats the purpose a bit. I think that, in this case (I guess this may be the problem with the algorithm style, I am not sure) maybe a more effective color contrast would make it better.

Seems like we should merge this in first, and address in w3c/json-ld-api#608 or in a separate PR that focuses on style.

**Review by anatoly-scherbakov — APPROVED** [review]
Thank you for tackling this @gkellogg. I was at a loss as to how to proceed, I must confess.

**Pull request merged**
